### ISSUE TITLE
xt::linalg::pinv crashes with both Visual Studio 2015 and Visual Studio 2017

### ISSUE THREAD

**Issue by AvocadoGinger** [QuantStack/xtensor-blas#102]
I'm using the xTensor master, with xTL 0.5.4 and OpenBlas (v0.2.14.1) on the Windows 10 x64.

When I tried to use **xt::linalg::pinv** as in QuanStack/xtensor-blas/test/test_linalg.cpp, line 225 in the **debug mode**:

`xt::xtensor<float, 2> d1 {{1.f, 2.f}};
auto r1 = xt::linalg::pinv(d1);`

With **Visual Studio 2017**, the test crashed right away with the following error:

> Message: Invalid parameter detected in function std::array<__int64, 1>::operator [], c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\array line 184, Expression: “array subscript out of 

> range”

With **Visual Studio 2015**, the test passed.  However it would crash with the same error as in Visual Studio 2017 when the debugger is attached.

Is it a known issue?  Any suggestion?

**Comment by AvocadoGinger** [comment]
I can reproduce same error with both VS2017 and VS2015(with debugger) with below simple array operations.  I also added equivalent python code at top (commented block).

`           // s = np.array([1.0])
            // u = np.array([[1.0]])
            // ut = np.transpose(u)
            // vww = s[..., np.newaxis]
            // m = vww * ut     // m = 1.0

            xt::xtensor<double, 1> s{ 1.f };
            xt::xtensor<double, 2> u{ { 1.f } };

            auto ut = xt::transpose(u);
            auto vww = xt::view(s, xt::all(), xt::newaxis());
            auto m = xt::eval(vww * ut);    // error!!

`

**Comment by wolfv** [comment]
Hi, there are some issues around initializing with initializer lists if they are small like this. Maybe the compiler uses a different constructor? Can you check the values in the shape variable?

**Comment by AvocadoGinger** [comment]
Hi,

In your first statement in the above comment "`there are some issues around initializing with initializer lists if they are small like this.`"

- Which "**_`some issues`_**" do you mean?  Is it general xTensor array issue or BLAS specific issue?  
- What do you mean by "**_`small`_**"?

For the values in the shape variable, the shape and strides values are as below;
```
s.m_shape = [1], s.m_strides = [0]
u.m_shape = [1,1], u.m_strides = [0,0] 
ut.m_shape = [1,1], ut.m_strides = [0,0]
vww.m_shape = [1,1], vww.m_strides=[-3689348814741910324, -3689348814741910324] , vww.m_backstrides=[-3689348814741910324, -3689348814741910324]   
```

The shapes are all look okay but the strides of the view looks strange.

**Comment by AvocadoGinger** [comment]
I found a root-cause of the issue. It’s a bug in the xTensor view code with below smallest error case.

**[smallest test case that produces the issue]**
```
        TEST_METHOD(Xtensor_tiny_view_err)
        {
            xt::xtensor<double, 1> s{ 1.0 };

            auto vw = xt::view(s, xt::all(), xt::newaxis());
            auto m = xt::eval(vw);
        }
```

**[Root-cause]
xtensor-master\include\xtensor\xview.hpp@1470**
```
    template <class CT, class... S>
    template <std::size_t... I>
    inline auto xview<CT, S...>::compute_strides_impl(std::index_sequence<I...>) const noexcept
    {
        return std::array<std::ptrdiff_t, sizeof...(I)>({
            (static_cast<std::ptrdiff_t>(xt::step_size(std::get<integral_skip<S...>(I)>(m_slices), 1)) * m_e.strides()[integral_skip<S...>(I) - newaxis_count_before<S...>(integral_skip<S...>(I))])...
        });
    }

```
m_e.strides()[integral_skip<S...>(I) - newaxis_count_before<S...>(integral_skip<S...>(I))]  size of the strides array is 1 but the index was 1.



**[Workaround]**
Current workaround what I’d suggested is;
```
        TEST_METHOD(Xtensor_tiny_view)
        {
            xt::xtensor<double, 1> s{ 1.0 };

            auto vw = xt::view(s, xt::all());
            auto vw2 = xt::view(vw, xt::newaxis());
            auto m = xt::eval(vw2);
        }

```
So, I’ve tested the PInv with below changes.  And now the Pinv issue is gone.

```
        auto ut = xt::transpose(u);
        auto vww1 = xt::view(s, xt::all());
        auto vww2 = xt::view(vww1, xt::newaxis());
        auto m = xt::eval(vww2 * ut);
        auto vtt = xt::transpose(vt);
        auto result = dot(vtt, m);

```

**Comment by wolfv** [comment]
I am looking at this now.

**Comment by wolfv** [comment]
@AvocadoGinger thanks a lot for the detailed error analysis!

I think I understand the bug well now -- on Windows, in Debug mode, the bounds of all accesses are checked. The values produced by the compute_strides function are correct (because the lhs of the multiplication will be `0`), but indeed we're accessing the strides member of the original (1D) expression out of bounds. 

It would be great to fix this but it will probably also complicate the template code a little bit ... let me see.

**Comment by wolfv** [comment]
Can you check wether this is fixed with https://github.com/QuantStack/xtensor/pull/1437 ?

**Comment by AvocadoGinger** [comment]
The workaround yesterday resolved the crash of pinv but the result of the pinv was not correct.

With the below workaround, the pinv now does not crash in debug mode and produces the correct result:

In file xtensor-blas/blob/master/include/xtensor-blas/xlinalg.hpp, line 1231

replace 
`        auto vww = xt::view(s, xt::all(), xt::newaxis());`

with 
`        auto vww = xt::strided_view(s, { xt::all(), xt::newaxis() });`

**Comment by AvocadoGinger** [comment]
With the [QuantStack/xtensor#1437](https://github.com/QuantStack/xtensor/pull/1437), the crash at [xview.hpp @ line 1470](https://github.com/QuantStack/xtensor/blob/master/include/xtensor/xview.hpp) resolved but the pinv now crashes with the same error at [xview.hpp @ line 1278](https://github.com/QuantStack/xtensor/blob/master/include/xtensor/xview.hpp)

**Comment by wolfv** [comment]
Hi @AvocadoGinger sorry for not fixing everything on the first try :/

Can you check out this attempt: https://github.com/QuantStack/xtensor/pull/1456

**Comment by AvocadoGinger** [comment]
Yes, it works.  Thank you!
