### ISSUE TITLE
xflens defining colliding macros

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xtensor-blas#121]
xflens defines a number of macros that have names that can easily collide such as `INTEGER` or `FLOAT`.

https://github.com/QuantStack/xtensor-blas/blob/0.16.1/include/xflens/cxxlapack/netlib/interface/lapack.in.h#L3-L33

This is an issue when using e.g. both `symengine` an `xtensor-blas` in the same notebook.

**Comment by guydavid** [comment]
This is an actual problem for me because I use xtensor-blas and dlib in the same project. The header file in question defines UNKNOWN to "void" and dlib uses that same identifier in an enum (inside a namespace though).

**Comment by wolfv** [comment]
Do you have time to open a PR? We would love those changes.

**Comment by guydavid** [comment]
It is possible to avoid this by including headers from xtensor-blas last.
