### ISSUE TITLE
Linker error with xtensor-blas on xlfens

### ISSUE THREAD

**Issue by BhayanakMoth** [QuantStack/xtensor-blas#122]
Hi, I am trying to use xtensor-blas on Windows. I have followed the steps to build it from source using Cmake properly and had no issues with that.
I am using MSVC to compile one of the examples that were given.

When I run: "cl xtens.cpp /I C:\Program1\include"
```
Output:
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x86
Copyright (C) Microsoft Corporation. All rights reserved.

xtens.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xlocale(319): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
Microsoft (R) Incremental Linker Version 14.16.27027.1
Copyright (C) Microsoft Corporation. All rights reserved.

/out:xtens.exe
xtens.obj
xtens.obj : error LNK2019: unresolved external symbol _cblas_ddot referenced in function "void __cdecl cxxblas::dot(int,double const *,int,double const *,int,double &)" (??$dot@H@cxxblas@@YAXHPBNH0HAAN@Z)
xtens.obj : error LNK2019: unresolved external symbol _cblas_dgemv referenced in function "void __cdecl cxxblas::gemv(enum cxxblas::StorageOrder,enum cxxblas::Transpose,int,int,double,double const *,int,double const *,int,double,double *,int)" (??$gemv@H@cxxblas@@YAXW4StorageOrder@0@W4Transpose@0@HHNPBNH2HNPANH@Z)
xtens.obj : error LNK2019: unresolved external symbol _cblas_dgemm referenced in function "void __cdecl cxxblas::gemm(enum cxxblas::StorageOrder,enum cxxblas::Transpose,enum cxxblas::Transpose,int,int,int,double,double const *,int,double const *,int,double,double *,int)" (??$gemm@H@cxxblas@@YAXW4StorageOrder@0@W4Transpose@0@1HHHNPBNH2HNPANH@Z)
xtens.obj : error LNK2019: unresolved external symbol _cblas_dsyrk referenced in function "void __cdecl cxxblas::syrk(enum cxxblas::StorageOrder,enum cxxblas::StorageUpLo,enum cxxblas::Transpose,int,int,double,double const *,int,double,double *,int)" (??$syrk@H@cxxblas@@YAXW4StorageOrder@0@W4StorageUpLo@0@W4Transpose@0@HHNPBNHNPANH@Z)
xtens.exe : fatal error LNK1120: 4 unresolved externals`
```

Program1\include\ folder contains folders: xtensor,xtensor-blas,xflens,xtl which contain the header fo respective libraries.
How can I solve this problem?

**Comment by BhayanakMoth** [comment]
I am facing the same problem on Ubuntu. After installing xtensor,xtl,xtensor-blas using cmake and make install I got the same error when I ran
g++ xtens.cpp -std=c++14
/tmp/cc9XTtYo.o: In function `cxxblas::If<int>::isBlasCompatibleInteger cxxblas::gemv<int>(cxxblas::StorageOrder, cxxblas::Transpose, int, int, double, double const*, int, double const*, int, double, double*, int)':
xtens.cpp:(.text._ZN7cxxblas4gemvIiEENS_2IfIT_E23isBlasCompatibleIntegerENS_12StorageOrderENS_9TransposeES2_S2_dPKdS2_S8_S2_dPdS2_[_ZN7cxxblas4gemvIiEENS_2IfIT_E23isBlasCompatibleIntegerENS_12StorageOrderENS_9TransposeES2_S2_dPKdS2_S8_S2_dPdS2_]+0x82): undefined reference to `cblas_dgemv'
/tmp/cc9XTtYo.o: In function `cxxblas::If<int>::isBlasCompatibleInteger cxxblas::syrk<int>(cxxblas::StorageOrder, cxxblas::StorageUpLo, cxxblas::Transpose, int, int, double, double const*, int, double, double*, int)':
xtens.cpp:(.text._ZN7cxxblas4syrkIiEENS_2IfIT_E23isBlasCompatibleIntegerENS_12StorageOrderENS_11StorageUpLoENS_9TransposeES2_S2_dPKdS2_dPdS2_[_ZN7cxxblas4syrkIiEENS_2IfIT_E23isBlasCompatibleIntegerENS_12StorageOrderENS_11StorageUpLoENS_9TransposeES2_S2_dPKdS2_dPdS2_]+0x8f): undefined reference to `cblas_dsyrk'
/tmp/cc9XTtYo.o: In function `cxxblas::If<int>::isBlasCompatibleInteger cxxblas::gemm<int>(cxxblas::StorageOrder, cxxblas::Transpose, cxxblas::Transpose, int, int, int, double, double const*, int, double const*, int, double, double*, int)':
xtens.cpp:(.text._ZN7cxxblas4gemmIiEENS_2IfIT_E23isBlasCompatibleIntegerENS_12StorageOrderENS_9TransposeES6_S2_S2_S2_dPKdS2_S8_S2_dPdS2_[_ZN7cxxblas4gemmIiEENS_2IfIT_E23isBlasCompatibleIntegerENS_12StorageOrderENS_9TransposeES6_S2_S2_S2_dPKdS2_S8_S2_dPdS2_]+0x94): undefined reference to `cblas_dgemm'
/tmp/cc9XTtYo.o: In function `cxxblas::If<int>::isBlasCompatibleInteger cxxblas::dot<int>(int, double const*, int, double const*, int, double&)':
xtens.cpp:(.text._ZN7cxxblas3dotIiEENS_2IfIT_E23isBlasCompatibleIntegerES2_PKdS2_S6_S2_Rd[_ZN7cxxblas3dotIiEENS_2IfIT_E23isBlasCompatibleIntegerES2_PKdS2_S6_S2_Rd]+0x35): undefined reference to `cblas_ddot'
collect2: error: ld returned 1 exit status

**Comment by SylvainCorlay** [comment]
@BhayanakMoth I both case, you need to link your project with BLAS.

**Comment by BhayanakMoth** [comment]
Got it, thanks.
