### ISSUE TITLE
dot product is slow!

### ISSUE THREAD

**Issue by ashmat98** [QuantStack/xtensor-blas#131]
I'm trying to reach the same performance as NumPy. With this code below I evaluate the speed of dot product using xtensor-blas:
`benchmark.cpp`
```c++
#include <iostream>
#include "xtensor/xarray.hpp"
#include "xtensor/xrandom.hpp"
#include "xtensor-blas/xlinalg.hpp"


xt::xtensor<double, 2> my_dot(xt::xtensor<double, 2> &A, xt::xtensor<double, 2> &B){
    auto start = std::chrono::steady_clock::now();

    xt::xtensor<double, 2> C = xt::linalg::dot(A, B);

    auto end = std::chrono::steady_clock::now();
    std::cout << std::chrono::duration<double, std::milli>(end - start) .count()
                << " ms" << std::endl;
    return C;
}


int main(int argc, char *argv[])
{
    for (int i=0;i<3;i++){
        xt::xtensor<double, 2> A = xt::random::randn({1000,2000}, 0., 1.);
        xt::xtensor<double, 2> B = xt::random::randn({2000,2000}, 0., 1.);

        xt::xtensor<double, 2> C = my_dot(A, B);
    }
    return 0;
}
```
I compile this with this command:
```bash
$ g++ benchmark.cpp -O3 -mavx2 -ffast-math \
 -I/home/--user--/install_path/include \
 -lblas -llapack \
 -DHAVE_CBLAS=1 \
 -o a.out
```
and I get
```bash
$ ./a.out
2395.9 ms
2415.98 ms
2461.93 ms
```
(Install_path/include contains all necessary libraries I.e xtensor, xtensor-blas...)
While when I multiply arrays of the same size in NumPy I get
```bash
$ python benchmark.py
76.17 ms
76.05 ms
79.00 ms
```
So this is mush SLOWER!
I've installed `sudo apt-get install libblas-dev liblapack-dev`
System:
```
Ubuntu: 18.04
gcc: 7.4.0
latest versions of xtensor libraries
```

Could you please help me with this?

**Comment by ashmat98** [comment]
I installed `libopenblas-dev` instead of `libblas-dev` and I got faster computation. I dont know why `blas` was slower than `openblas` (`blas` was using single thread) but I got what I needed. I'm closing the issue

**Comment by wolfv** [comment]
thanks for figuring it out :) 

NumPy and xtensor-blas both use BLAS so the performance should be dependent on whcih BLAS library you use. OpenBLAS and MKL are probably the fastest.
