### ISSUE TITLE
Return types

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xtensor-blas#15]
Currently, xtensor-blas tries to return xtensors if the dimensions of the return type are known. I'm not sure if that's a good idea, and in some cases it changes the interface a bit (e.g. in `lstsq` the solution is always in 2D which is different from numpy).

Also, people might want to change the dimensionality of the return array.

Should we make the return type selectable, or use xarray?

**Comment by JohanMabille** [comment]
That is not the first time that we would like to use ``xtensor`` when we know the number of dimensions for performance considerations and keep the possibility to reshape it further in the code.
Actually, you could return an ``xtensor`` and let the user copy it into an ``xarray`` if she needs to reshape, but that would be a performance hit.
I think we could solve that problem by adding a move constructor / assign operator from an ``xtensor`` in ``xarray`` and vice versa.

**Comment by wolfv** [comment]
We can also use the xstridedview by the way. and it could have fixed shape/strides type, too :)

**Comment by JohanMabille** [comment]
That's another way of doing it, but this is less natural than just moving the xtensor / xarray, unless you want to keep the origin xtensor / xarray unchanged.

Anyway, whatever the solution you choose to "reshape", you can go ahead with returning xtensor where you can :)

**Comment by wolfv** [comment]
There is another consideration actually, regarding the return types. In NumPy, `det` (and other operation) will be performed along the last two axes. So if the input has dimension > 2, the output will be an array. But currently the output of `det` in xtensor-blas is a scalar. 

I was thinking maybe we could use some sort of variant type with automatic casting upon assignment? 
That way, we could easily return scalar types if `det` of dimension 2, and array if dimension > 2... 

Or should we do some sort of automatic cast if `double a = xarray<double>({1,2,3,4})` such that the first element of the xarray would be assigned to the scalar?

**Comment by wolfv** [comment]
I think for most / all cases the return type is going to be xarray. And in the future with the new shape type, they'll be just as fast as xtensors.
