### ISSUE TITLE
crash on destruction of result of dot

### ISSUE THREAD

**Issue by xylosper** [QuantStack/xtensor-blas#16]
Next code crashes on destruction of `a3`:

```cpp
    {
        xt::xarray<double> a1{1, 2};
        {
            xt::xarray<double> a2{
                {1, 1, 1},
                {1, 2, 3}
            };
            {
                xt::xarray<double> a3 = xt::linalg::dot(a1, a2);
                std::cout << a3 << std::endl;
            } // crashes here
        }
    }
```

Also, I expected (3 5 7) as result but the console says {3, 5} (wrong result, wrong shape).
Is this a bug? Or, maybe I'm using xtensor-blas in wrong way, here?

**Comment by wolfv** [comment]
Hi and thanks for the first ever bug report on xtensor-blas!

You're absolutely correct, the shape of the result was wrong. Therefore, blas probably attempts to write into unallocated memory which is also why it's crashing on destruction. 

The bug is fixed and a test was added in #17. After the test suite builds on travis, I'll merge.

Cheers,

Wolf

**Comment by wolfv** [comment]
fixed! thanks again.

**Comment by wolfv** [comment]
if you have any other feedback about xtensor/xtensor-blas, feel free to join us on gitter: https://gitter.im/QuantStack/Lobby 

We're always happy to hear about use cases and potential improvements.

**Comment by xylosper** [comment]
Thank you for fast response. I checked new code and found one problem. `has_raw_data_interface` doesn't exist in `xt::detail` namespace. It resides `xt` namespace instead in latest revision of xtensor repo.

**Comment by SylvainCorlay** [comment]
@xylosper thanks for the reports!

Quick side note: xtensor-blas has not had a release tagged yet. However, when it is, we recommend using tagged / released versions of the dependencies rather than the state at a given point in time of the repositories.
