### ISSUE TITLE
xt::blas::gemm doesn't work for non-square matrix and transpose_A is true

### ISSUE THREAD

**Issue by ecoronel3** [QuantStack/xtensor-blas#26]
Hey guys,
I noticed that there's a bug in the gemm function. If you try to calculate M = X'*X in the following way:

    xt::xarray<double> X = {{1, 2, 3},
                            {1, 2, 3}};
    std::vector<int> shape = {3, 3};
    xt::xarray<double> M;
    M.reshape(shape);

    xt::blas::gemm(X, X, M, xt::xscalar<double>(1), xt::xscalar<double>(0), true, false);

Cheers

**Comment by wolfv** [comment]
Hey, thanks a lot for this perfect bug report (with reproducible example). 
I've tried to fix it in the commit #27, and added tests. Let me know if it works for you. 

Also, if you have additional feedback, feel free to let us know. 

Cheers,

Wolf

**Comment by wolfv** [comment]
Looks like it's building fine everywhere, so I am going to merge as soon as the OS X build is done.

**Comment by wolfv** [comment]
Hey @ecoronel3,

just to notify you, if you're using the latest master, we have removed the need to use `xscalar` (just using a double now) and the order of the `transpose` argument has changed, so that it's consistent with `gemv`.

Sorry for the API breakage,

Wolf
