### ISSUE TITLE
No installpath/include/xtensor-blas/flens directory after installation

### ISSUE THREAD

**Issue by tkloczko** [QuantStack/xtensor-blas#52]
Hi,

When I install xtensor-blas, the content of the directory `xtensor-blas/flens` is directly copied into `installpath/include/` . It follows that the variable `FLENS_INCLUDE_DIR` provided by `xtensor-blasConfig.cmake` is not defined.
Furthermore, the project name in the `xtensor-blasConfig.cmake` writes ***xtensor_blas*** while one could expect to find ***xtensor-blas*** instead.

If I correct CMakeLists by appending `xtensor-blas/flens` for the install include path and if I use variable `${xtensor_blas_INCLUDE_DIRS}`, I am able to use xtensor-blas as third-party library.

By the way, I really like the work you are doing ;-) !

Cheers,

Thibaud Kloczko
thibaud.kloczko@inria.fr

**Comment by tkloczko** [comment]
Hi,

We tried to use conda installation on MacOs and we met the same issue. Furthermore the version of xtensor required for xtensor-blas was older than the one provided by the single installation of xtensor (0.13 vs 0.15.1).

So we made xtensor-blas installation as quiet in all our projects since its use is not mandatory at the moment.

Anyway, we installed xtensor on linux (ubuntu, fedora, centos), MacOsX and windows without any trouble. It enabled us to convince researchers to use it in their production code :-) !

Sincerely,

Thibaud.

**Comment by wolfv** [comment]
Hi Thibaud,

first of all thanks for using our stuff! It's really exciting to hear (I've seen a lot of cool robotics stuff coming out of INRIA! :)

I'm releasing xtensor-blas 0.9.0 right now, which contains an important fix for SVD.
After that, I think we can fix the installation on OS X and release an 0.9.1 shortly. 

Thanks for the detailed bug report.

Cheers,

Wolf

**Comment by tkloczko** [comment]
Hi Wolf,

Thanks for your answer. I will soon test this next release :-) !

Sincerely,

Thibaud.

**Comment by wolfv** [comment]
Hi Thibaud,

we changed how FLENS is installed, and just released 0.10.0 which should definitly fix the issue. We'd be curious if you could try and let us know?

Now, xtensor-blas and xflens should both be installed in `include/...`

Cheers!

Wolf

**Comment by tkloczko** [comment]
Hi Wolf,

I checkouted on master branch and it works very well ! Thanks a lot for that.

Actually, I am playing with xtensor and xtensor-blas in [dtk-linear-algebra-dense](https://github.com/d-tk/dtk-linear-algebra-dense) and I will certainly have many many questions !

For more details, here are the concerned files:
* [xvector_static_engine.h](https://github.com/d-tk/dtk-linear-algebra-dense/blob/feature/xtensor/src/xvector_static_engine.h)
* [xvector_static.h](https://github.com/d-tk/dtk-linear-algebra-dense/blob/feature/xtensor/src/xvector_static.h)
* [xtensorVectorTest.cpp](https://github.com/d-tk/dtk-linear-algebra-dense/blob/feature/xtensor/tst/dtkVector/xtensorVectorTest.cpp)

I modified also my xtensor-blas by adding a convenient `blas` method so that I can write the following
```
xt::xtensor<double, 1> t0 = {1, 2, 3, 4, 5, 6, 7};
xt::xtensor<double, 1> t1 = {2, 3, 4, 5, 6, 7, 8};

double rest = xt::blas::dot(t0, t1);
```
And the reason people at Inria like using libraries such as FLENS, Blaze or EIgen is that they can write the following:
```
xt::xvector_static<double, 7UL> v0 = {1, 2, 3, 4, 5, 6, 7};
xt::xvector_static<double, 7UL> v1 = {2, 3, 4, 5, 6, 7, 8};

double resv = v0 * v1;
```
I  am sure it is possible to add some tag in xtensor to reach the same but is is not the scope of the current issue ;-) !

Thanks again !

See you,

Thibaud.

**Comment by wolfv** [comment]
Hi Thibaud, 

interesting. Do you want to come over on gitter and have a chat? 

http://gitter.com/QuantStack/Lobby ? :) 

So you're using FLENS and xtensor in dtk? What's the goal of the project (just curious)?

Yeah, about overloading the ` * ` operator ... we've decided to go with NumPy conventions and use `dot`. However, one could probably make some inheriting class (e.g. `xmatrix : xtensor<...>`) that could overload the ` * ` to matrix multiplication. Too bad C++ doesn't support the ` @ ` operator :)

**Comment by wolfv** [comment]
btw you can also always do 

`using namespace xt::linalg` to import the entire namespace, or
`namespace lg = xt::linalg` to be able to do `lg::dot` or what you prefer :)

**Comment by alamj** [comment]
Hi Wolf,

I cannot compile the code if xtensor-blas is used. For instance, if I have the following line:
std::cout << xt::linalg::solve(arr,b) << std::endl;

I get a lot of error, a part of which is pasted below:

/opt/xtensors/xtensor-blas/include/xflens/cxxlapack/interface/gesv.tcc:44:1: note: candidate: ‘IndexType cxxlapack::gesv(IndexType, IndexType, float*, IndexType, IndexType*, float*, IndexType) [with IndexType = int]’
   44 | gesv(IndexType  n,

I am on a Fedora 31 box. I would appreciate any help to get a work around.

Jahrul
