### ISSUE TITLE
import fail -- Symbol not found: _dgetrf_

### ISSUE THREAD

**Issue by yashaach** [QuantStack/xtensor-blas#63]
I used the cookiecutter to start my own development environment (https://github.com/QuantStack/xtensor-python-cookiecutter). After verifying that it works, I simply added a new function that involves xt::linalg::inv to test out the linear algebra library.

`inline xt::pyarray<double> example3(xt::pyarray<double> &m)
{
  return xt::linalg::inv(m);
}`

And also added the include lines

`#include "xtensor-blas/xblas.hpp"
#include "xtensor-blas/xlinalg.hpp"`

It did compile with the existing setup.py, but upon import I get this error from the interpreter.

> ImportError: dlopen(xtensor-example-extension/xtensor_example_extension.cpython-36m-darwin.so, 2): Symbol not found: _dgetrf_
  Referenced from: xtensor-example-extension/xtensor_example_extension.cpython-36m-darwin.so
  Expected in: flat namespace

Does anyone know why this is happening? Do I need to add something to setup.py?

**Comment by SylvainCorlay** [comment]
Thanks for reporting. `dgetrf` is a symbol from BLAS< so it seems that it is not finding the BLAS library.

I will look into your example tomorrow (it is getting late here).

**Comment by wolfv** [comment]
Did you add something along the lines of 

```
    find_package(BLAS REQUIRED)
    find_package(LAPACK REQUIRED)

    target_link_libraries(PUT_TARGET_NAME_HERE ${BLAS_LIBRARIES} ${LAPACK_LIBRARIES})
```
to your CMakeLists? It looks to me like you're not linking a BLAS implementation

**Comment by wolfv** [comment]
Or rather, LAPACK (since taking the inverse of a matrix calls the `dgetrf` routine of the LAPACK library).

**Comment by yashaach** [comment]
Sorry do you mean adding these during manual installation of xtensor-blas (and therefore do not use 'conda install -c conda-forge xtensor-blas") ? For building my own library it is still the same "python setup.py build" right?

**Comment by yashaach** [comment]
Oh I think the following method works -- add `libraries=['lapack', 'blas'],` to Extension in ext_modules, in setup.py of the xtensor-example-extension. I believe this adds the flags `-llapack -lblas` in the last step of the build when `python setup.py build` is called.

**Comment by wolfv** [comment]
awesome, exactly that's what's needed. We usually use a cmake-based build system, so I responded with the CMake instructions, sorry. 

We are planning to document much better how to properly link against BLAS and LAPACK.

Note that by just appending `-llapack -lblas` I am not sure which library your compiler will pick (i.e. the one in the conda environment or your systems one, if you have one installed). You might want to pass additional flags to make sure that you're picking the right one if you are concerned about that.

**Comment by wolfv** [comment]
I am going to close this issue and open a new one for the documentation.
