### ISSUE TITLE
linalg::dot does not work well with view

### ISSUE THREAD

**Issue by yashaach** [QuantStack/xtensor-blas#66]
Here is a simple extension of the dot function. The inputs are assumed to be 3-d numpy ndarrays, and it just returns the dot product of the first slices of the inputs.

```
inline xt::pyarray<double> dot3d(xt::pyarray<double> &ar0,
                                 xt::pyarray<double> &ar1)

{
  xt::xarray<double> ar0_x(ar0);                                                                                                                                                                
  xt::xarray<double> ar1_x(ar1);                                                                                                                                                                
  auto out = xt::linalg::dot(xt::view(ar0_x, 0),
                             xt::view(ar1_x, 0));
  return xt::pyarray<double> (out);
}
```

This appears to compile without issues. Here's the output from the interpreter --

`
>>> temp1 = np.random.randn(50).reshape(2,5,5)                                                                                                                                                              
>>> temp2 = np.random.randn(20).reshape(2,5,2)                                                                                                                                                              
>>> temp3 = am_ext.dot3d(temp1, temp2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No valid layout chosen.
`

Is this an expected behavior? 

The context here is, I'm trying to write a function that takes two numpy 3-d arrays and single 1-d index, and apply dot function on the corresponding slices of the inputs based on the index.

**Comment by wolfv** [comment]
Hi! 
Nope, that's not expected behavior. We aim to operate seamlessly on views (without copying, if possible).

I'll have to look into this.

**Comment by yashaach** [comment]
One thing I noticed is that the same code does not behave the same way on Ubuntu and Mac. On my ubuntu, it compiles but does not run. On Mac, it does not compile. Here are the error messages.

/anaconda3/include/xtensor/xutils.hpp:511:103: error: type 'const 
    xt::xview<xt::xarray_container<xt::uvector<double, std::__1::allocator<double> >, 
    xt::layout_type::row_major, xt::svector<unsigned long, 4, std::__1::allocator<unsigned long>, true>, 
    xt::xtensor_expression_tag> &, int> &' cannot be used prior to '::' because it has no members
      ...bool value = decltype(test<T>(std::declval<const std::add_pointer_t<typename T::value...

/anaconda3/include/xtensor-blas/xlinalg.hpp:604:20: error: no matching function for call to
      'view_eval'
        auto&& t = view_eval<T::static_layout>(xt.derived_cast());

**Comment by SylvainCorlay** [comment]
@yashaach can you update xtensor-blas on the platform where you have this error?

**Comment by yashaach** [comment]
Oh that solves the compilation problem. Now both sides produce the same error "no valid layout chosen". On the Mac side the python interpreter crashes, while on the Ubuntu side the interpreter manages to return back to the prompt.

**Comment by wolfv** [comment]
hey, so the quick fix would be to use `dot(xt::eval(view), xt::eval(view));` in front of the arguments.
I expect to have a real fix for this issue by the beginning of next week.

**Comment by SylvainCorlay** [comment]
@wolfv can we close this one?

**Comment by wolfv** [comment]
I'm working on something related rihgt now, gonna check on this after.

**Comment by wolfv** [comment]
This works now thanks to the dynamic `layout()` function on view that computes if we have a contiguous layout.

**Comment by csango** [comment]
This bug is still exist:
```

    xt::xtensor_fixed<double, xt::xshape<4, 4> > c = xt::linspace<double>(1.0, 16, 16);
    std::cout << c << std::endl
              << std::endl;

    auto v1 = xt::view(c, xt::range(0, 2), xt::range(0, 2));

    std::cout << v1 << std::endl
              << std::endl;

    auto v2 = xt::linalg::dot(v1, v1);
    std::cout << v2 << std::endl;
```

I get the same error under Ubuntu.
`
g++  --std=c++20 -DXTENSOR_USE_FLENS_BLAS -I./xtensor/include -I./xtl/include -I./xtensor-blas/include  seepy_test_manual.cpp -o test`

**Comment by wolfv** [comment]
@csango can you open a new issue and post the versions of xtensor / xtensor-blas you're using?

Thanks!
