### ISSUE TITLE
Inconsistent install path for xtensor-blasConfig.cmake with respect to the xtensor family

### ISSUE THREAD

**Issue by tkloczko** [QuantStack/xtensor-blas#70]
Hi Guys,

As said in the title, `xtensor-blasConfig.cmake` is installed by default in `share/cmake/xtensor-blas` folder while for the rest of the family such files are installed in `lib/cmake/family-name`.

Of course, this not urgent :-) !

Cheers,

Thibaud.

**Comment by SylvainCorlay** [comment]
Thanks @tkloczko for the report. Indeed, that was an oversight on our side. Just opened a fixup PR.
