### ISSUE TITLE
xt::linalg::lstsq is not working when M > N

### ISSUE THREAD

**Issue by potpath** [QuantStack/xtensor-blas#89]
The following minimal test fails
```c++
TEST(xlinalg, lstsq_m_lessthan_n_minimal)
{
    xarray<double> arg_0 = {{ 0., 1.}};
    xarray<double> arg_1 = {1.};

    auto res = xt::linalg::lstsq(arg_0, arg_1);
}
```
The error is `"Could not find workspace size for gelsd."`

According to http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga94bd4a63a6dacf523e25ff617719f752.html#ga94bd4a63a6dacf523e25ff617719f752:
`ldb` should be `>= max(1,max(M,N))`.

From
https://github.com/QuantStack/xtensor-blas/blob/9725a505db5c24f4037f9df4691171037e9f7026/include/xtensor-blas/xlapack.hpp#L693-L702
this looks like `b` and `ldb` is not handled differently when `M > N` .

**Comment by wolfv** [comment]
I'm looking into this.

**Comment by wolfv** [comment]
This is fixed with the latest PR.
