### ISSUE TITLE
xblas::gemm cannot take a variable of type xt::pyarray<double> as output

### ISSUE THREAD

**Issue by apepkuss** [QuantStack/xtensor-blas#97]
I tried some test code on xblas::gemm, and got some error message. I just wonder if I used xblas::gemm in a correct way. I got the test code from https://github.com/QuantStack/xtensor-blas/blob/master/test/test_blas.cpp, and made some changes. 

The original code is shown as below. It can be compiled with no errors.
```c++
xt::xarray<double> X = {{1, 2, 3}, {1, 2, 3}};
auto M = xt::xarray<double>::from_shape({3, 3});
xt::blas::gemm(X, X, M, true, false, 1.0, 0.0);
```
Then, I made a change on the second line of the original code. 
```c++
xt::xarray<double> X = {{1, 2, 3}, {1, 2, 3}};
auto M = xt::pyarray<double>::from_shape({3, 3});
xt::blas::gemm(X, X, M, true, false, 1.0, 0.0);
```
When I compiled the new code, I got the error message: "... xtensor-blas/xblas.hpp:176:40: error: static assertion failed: GEMM result layout cannot be dynamic. ..." Could you please explain the error in detail? Thanks a lot.

**Comment by wolfv** [comment]
this is an "issue" in the python bindings. We currently use a dynamic default layout in the bindings which cannot be used in the blas bindings -- it needs to be statically set to `row_major` like so:

```
pyarray<double, layout_type::row_major> res;
```

We (I) want to change this behavior since a while. I think there should also be an open issue in xtensor-python about it.

**Comment by wolfv** [comment]
Of course you can also do `pyarray<double, layout_type::row_major>::from_shape(...)`

**Comment by wolfv** [comment]
and btw the higher level interface is `xt::linalg::dot`, just like it's done in numpy, with broadcasting etc.

**Comment by wolfv** [comment]
Did this work? closing for now.
